name: 01-Building-Blocks
on: workflow_dispatch
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello World"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps: 
            - name: Successfull step
              run: |
                echo "i will succeed"
                exit 0
            - name: Say goodbye
              run: echo "goodbye!!"
